Repository bobbyiliev/introduction-to-sql, pull requests merged in 2021-10, with the labels that each got.

#14 Fixed the Typos
  ebook/en/content/005-select.md
Labels: hacktoberfest-accepted

#17 🐛 [Bug]: upated contributing.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#18 Removed redundant database name
  ebook/en/content/003-creating-tables.md
Labels: hacktoberfest-accepted

#19 🚀[Feat]: Added Create table as statement
  ebook/en/content/003-creating-tables.md
Labels: enhancement, hacktoberfest-accepted

#21 Fix Typos
  ebook/en/content/004-basic-syntax.md
  ebook/en/content/009-update.md
Labels: bug, hacktoberfest-accepted

#26 rename table
  ebook/en/content/003-creating-tables.md
Labels: hacktoberfest-accepted

#24 fixed few typos in the CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#32 Added more use cases of SELECT clause
  ebook/en/content/005-select.md
Labels: enhancement, hacktoberfest-accepted
